### ISSUE TITLE
SUGGESTION: allow using arbitrary model

### ISSUE THREAD

**Issue by Gusarich** [ex3ndr/llama-coder#11]
I think it would be nice to have the possibility to utilize any model instead of being limited by the list you provide in settings

**Comment by VfBfoerst** [comment]
Is it a possibility to set the FIM settings via extension settings and  then use the given settings as variables in `src/prompts/adaptors/adaptPrompt.ts` ?  
Or is it explicitly wanted to fix the model selection?  
Just wondering if it is easier for possible future models :)

**Comment by ex3ndr** [comment]
I will research possibility of doing so, what specific model you would like to try?

**Comment by Gusarich** [comment]
> I will research possibility of doing so

I thought it wouldn’t be a hard task.. Don’t these models work in a similar way through ollama?

> what specific model you would like to try?

I was thinking about trying mixtral.

**Comment by ex3ndr** [comment]
The problem is that most networks are not trained for such task. If something is trained for chat-like behaviour it won't work as code completion tool, mixtral could work to some extent, but it wasn't trained to be able to insert code between two other parts of the code and therefore it wouldn't work.

**Comment by ex3ndr** [comment]
Meanwhile, i have released a new version that allows to pick any model (that accepts compatible format)
