### ISSUE TITLE
Ignoring download reset

### ISSUE THREAD

**Issue by oderwat** [ex3ndr/llama-coder#16]
It seems that ignoring the download of a model will disable any download, even when the model is changed. There should be a way to reset this.

**Comment by ex3ndr** [comment]
Original complaint was about downloading and wasting metered data limits on it and therefore it was done like this. Right now you can reset it only by restarting VS Code, or you can just execute "ollama pull <imagename>" to make it work.

**Comment by HelmholtzW** [comment]
I see this issue is closed. However, I have a similar problem. I want to use a custom model via Ollama, to which I gave the name copilot. Running `ollama run copilot` works in the terminal, and other extensions also work well. However, when I started Llama Coder and set the custom model to 'copilot,' the extension told me that copilot wasn't downloaded and asked if I wanted to download it. I clicked on 'No,' and ever since, nothing happens. Looking at the logs, I see "Ingoring since the user asked to ignore download.".

How can I use this model, as I already manually created it using the gguf file and ollama create?
Thanks in advance!
